export const FETCH_CURRENCY_REQUEST = 'FETCH_CURRENCY_REQUEST';
export const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';
export const FETCH_CURRENCY_FAILURE = 'FETCH_CURRENCY_FAILURE';

export const FETCH_CONVERSION_REQUEST = 'FETCH_CONVERSION_REQUEST';
export const FETCH_CONVERSION_SUCCESS = 'FETCH_CONVERSION_SUCCESS';
export const FETCH_CONVERSION_FAILURE = 'FETCH_CONVERSION_FAILURE';

export const FETCH_EXCHANGERATE_REQUEST = 'FETCH_EXCHANGERATE_REQUEST';
export const FETCH_EXCHANGERATE_SUCCESS = 'FETCH_EXCHANGERATE_SUCCESS';
export const FETCH_EXCHANGERATE_FAILURE = 'FETCH_EXCHANGERATE_FAILURE';
